version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.2.1 # the primary container, where your job's commands are run
    branches: 
      only: 
        - gh_pages
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command