version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.2.1 # the primary container, where your job's commands are run
    branches: 
      only: 
        - gh_pages
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm run build
      - run: echo "hello world" # run the `echo` command
      - run:
          name: remove files and dirs which exclude `dist`
          command: /bin/ls -A | grep -v -E '^(dist$|.git)' | xargs rm -rf
      - run:
          name: move `dist` dir to current dir
          command: mv ./dist/* ./
      - run:
          name: deploy to gh-pages
          command: |
            git config --global user.name  "uehara-mech"
            git config --global user.email "starlight00731@gmail.com"
            git add .
            git commit -m "Publish [ci skip]"
            git checkout -B master
            git push -u origin master --force